[workspace]
authors = ["Opher Donchin <donchin@bgu.ac.il>"]
channels = ["conda-forge","nvidia"]
name = "pymc_environment"
platforms = ["linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]

#[system-requirements]
#cuda = "13.0"

[dependencies]
arviz = "*"
pymc = "*"
python = "*"
ipython = "*"
ipykernel = "*"
ipywidgets = "*"
ipympl = "*"
graphviz = "*"
notebook = "*"
matplotlib = "*"
numpy = "*"
numba = "*"
scipy = "*"
pandas = "*"
xarray = "*"
pip = "*"
pydot = "*"
nbconvert = "*"
jupytext = "*"
networkx = "*"
kedro = "*"
nutpie = "*"
bambi = "*"
preliz = "*"
threadpoolctl = "*"
numpyro = "*"
jax = "*"

[pypi-dependencies]
pymc-extras = { git = "https://github.com/opherdonchin/pymc-extras.git", rev = "main" }
kulprit = "*"
